### ISSUE TITLE
Installing question

### ISSUE THREAD

**Issue by interose** [shamblett/mqtt_client#10]
Hi, I tried to install the package but it gives me the following error:
```
Running "flutter packages get" in myapp...
Package mqtt_client has no versions that match >=1.5.0 <2.0.0 derived from:
- myapp depends on version ^1.5.0
pub get failed (1)
```

I tested it with a fresh new app:
```
Running "flutter packages get" in myapp...           18,1s

[✓] Flutter is fully installed. (Channel beta, v0.1.5, on Mac OS X 10.13.3 17D102, locale de-DE)
[✗] Android toolchain - develop for Android devices is not installed.
[✓] iOS toolchain - develop for iOS devices is fully installed. (Xcode 9.2)
[✗] Android Studio is not installed. (not installed)
[✓] VS Code is fully installed. (version 1.21.1)
[✓] Connected devices is fully installed. (1 available)
```

I also tried to install version 1.4 or 1.3, but I always get the same message.
Contents of pubspec.yaml:
```
name: myapp
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.0
  mqtt_client: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
```

Any help or hint is greatly appreciated!

**Comment by shamblett** [comment]
Hmm, Iv'e never installed on Flutter but I guess that shouldn't matter, try relaxing the version number, what happens if you specify '<=2.0.0' ?

**Comment by interose** [comment]
Ah okay  - sorry. I searched via https://pub.dartlang.org/ and found your lib which is marked with the flutter badge.

I tried to add your lib via
```
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.0
  mqtt_client: '<=2.0.0'
```
but It gives me the following
```
> flutter packages get
Running "flutter packages get" in myapp...
Package mqtt_client requires SDK version >=1.8.0 <2.0.0-dev.infinity but the current SDK is 2.0.0-edge.0d5cf900b021bf5c9fa593ffa12b15bcd1cc5fe0.
pub get failed (1)
```

Because flutter is really new and there is no stable branch nor I could choose a special SDK version, I guess this is to early ;)

No big deal, I already have a working mqtt swift example and tried to create a demo app with react native and/or flutter.
