### ISSUE TITLE
Dependency incompatibility on 9.4.0 with FLUTTER stable

### ISSUE THREAD

**Issue by wagner-rebello** [shamblett/mqtt_client#304]
When trying to use mqtt_client version 9.4.0 with flutter **stable** _(2.2.3)_ there is a dependency incompatibility that cannot be solved by the developer.
Flutter uses an old version of **meta** on **_test_** and **_localization_** internal libraries.

```
Because every version of flutter_test from sdk depends on meta 1.3.0 and mqtt_client >=9.4.0 depends on meta ^1.7.0, flutter_test from sdk is incompatible with mqtt_client >=9.4.0.

So, because Brise depends on both mqtt_client 9.4.0 and flutter_test any from sdk, version solving failed.
pub get failed (1; So, because Brise depends on both mqtt_client 9.4.0 and flutter_test any from sdk, version solving failed.)
exit code 1
```

Pubspec chunk:
```
environment:
  sdk: ">=2.10.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: 1.0.0 # Icones nativos do iOS
  uuid: 3.0.4 # Gera UUIDs para acesso ao Broker. (MIT)
  mqtt_client: 9.4.0 # Acesso MQTT (MIT)
  protobuf: 1.0.1 # Biblioteca para uso de Protocol Buffer (BSD)
  http: 0.13.3 # Acesso API Rest (BSD)
  validate: 1.7.0 # Auxilia a validar Forms (Apache 2.0)
  connectivity: 3.0.6 # Verifica conectividade de rede e qual a procedencia (wifi, 4g)
  wifi_iot: 0.3.3 # Apoio para controle de Wifi (MIT)
  sqflite: 2.0.0+3 # Acesso SQLite (MIT)
  circular_menu: 1.1.0 # Menu circular (MIT)
  flutter_slidable: 0.6.0 # Menu dentro de lista (iOS) (MIT)
  path_provider: 2.0.1 # Auxilia a gerenciar diretorios entre iOS e Android (BSD)
  google_maps_flutter: 2.0.3 # API do Google MAPS (BSD)
  permission_handler: 8.1.3 # Auxilia na requisição de permissão de uso de sensores. (MIT)
  location: 4.3.0 # Biblioteca de GPS (MIT)
  pull_to_refresh: 1.6.5 # Refresh de puxar nas listas (MIT)
  flutter_svg: 0.22.0 # Renderização de imagens em SVG (MIT)
  uni_links: 0.4.0 # Deep Linking (Recover de Senha) (BSD)
  url_launcher: 6.0.3 # Utilitario para abrir links fora do app (BSD)
  table_calendar: 2.3.3 # Widget de calendario (Apache 2.0)
  fl_chart: 0.36.2 # Gerador de graficos linha/pizza/etc... (BSD)
  share: 2.0.1 # Compartilhamento de dados (Via API do sistema.) (BSD)
  crypto: 3.0.1 # Calculo de HASH (BSD)
  flutter_local_notifications: 6.1.0 # Notificações PUSH (BSD)
  loading_animations: 2.2.0 # Loader (MIT)
  step_progress_indicator: 1.0.0 # Barra de porcentagem (MIT)
  flutter_barcode_scanner: 2.0.0 # Leitor de QRCode
  flutter_intro: 0.7.0 # Para fazer tutorial do tipo Tooltip
  wakelock: 0.5.1 # Para bloquear a tela ligada na calibração.
  package_info: 2.0.0 # Pacote que pega a versão daqui do Pubspec e disponibiliza para o Codigo
  auto_size_text: 3.0.0-nullsafety.0 # Texto auto ajustavel (MIT)
  syncfusion_flutter_gauges: 19.1.69 # TESTE de WIDGETs (Licença Proprietaria)
  mailer: 5.0.1 # Envio de email. (MIT)

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: 0.9.0
```
